questions = [
  { image: "assets/buckhouse.jpg",
    imageSource: "dailymail.co.uk",
    question: "Let's start easy! What building is this?",
    answers: ["Windsor Castle", "Westminster Abbey", "Buckingham Palace", "Marlborough House"],
    correctAnswer: 2,
    answerFeedback: "Buckingham Palace is the London residence and principal workplace of the reigning monarch of the United Kingdom. Located in the City of Westminster, the palace is often at the centre of state occasions and royal hospitality.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Buckingham_Palace"
  },
  { image: "assets/queenvic.jpg",
    imageSource: "biography.com",
    question: "Time for a historical figure! Of whom is this a painting?",
    answers: ["Queen Elizabeth I", "Margaret Thatcher", "Queen Elizabeth II", "Queen Victoria"],
    correctAnswer: 3,
    answerFeedback: "Victoria (Alexandrina Victoria; 24 May 1819 to 22 January 1901) was Queen of the United Kingdom of Great Britain and Ireland from 20 June 1837 until her death. From 1 May 1876, she had the additional title of Empress of India.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Queen_Victoria"
  },
  { image: "assets/yp.jpg",
    imageSource: "bbc.co.uk",
    question: "Hungry yet? Let's talk food. Eaten regularly, what are these treats?",
    answers: ["Spotted Dick", "Yorkshire Pudding", "Bubbles & Squeek", "Toad in a Hole"],
    correctAnswer: 1,
    answerFeedback: "Yorkshire pudding is an English dish made from batter consisting of eggs, flour, and milk or water. The dish is sometimes served with beef and gravy and is a staple of the traditional British Sunday roast. It may also be served as a dessert.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Yorkshire_pudding"
  },
  { image: "assets/birm.jpg",
    imageSource: "finedininglovers.com",
    question: "Time to think about the British map.  Pictured above, this is the second largest city in England.",
    answers: ["Bath", "Manchester", "Birmingham", "Liverpool"],
    correctAnswer: 2,
    answerFeedback: "Birmingham is a city and metropolitan borough in the West Midlands of England. It is the largest and most populous British city outside London, with a population in 2014 of 1,101,360",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Birmingham"
  },
  { image: "assets/sandringham.jpg",
    imageSource: "greatrail.com",
    question: "A well known private home in the countryside, usually occupied around Christmas, what is the name of this home?",
    answers: ["Sandringham House", "Castle of Mey", "Highgrove House", "Anmer Hall"],
    correctAnswer: 0,
    answerFeedback: "Sandringham House is near the village of Sandringham in Norfolk, England. The house is privately owned by Queen Elizabeth II and is located on the royal Sandringham Estate, which lies within the Norfolk Coast Area of Outstanding Natural Beauty.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Sandringham_House"
  },
  { image: "assets/BD.jpg",
    imageSource: "theguardian.com",
    question: "The only British Prime Minister of Jewish birth, this man twice served during the reign of Queen Victoria.  Who is he?",
    answers: ["Winston Churchill", "William Gladstone", "William Lamb", "Benjamin Disraeli"],
    correctAnswer: 3,
    answerFeedback: "Benjamin Disraeli, 1st Earl of Beaconsfield, KG, PC, FRS (21 December 1804 to 19 April 1881) was a British politician and writer, who twice served as Prime Minister. He played a central role in the creation of the modern Conservative Party, defining its policies and its broad outreach.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Benjamin_Disraeli"
  },
  { image: "assets/bath.jpg",
    imageSource: "holeinthedonut.com",
    question: "Known for significant Roman architecture and as the home of writer Jane Austen, this town, 156km west of London, is: ",
    answers: ["Bath", "Bristol", "Somerset", "Avon"],
    correctAnswer: 0,
    answerFeedback: "Bath is a city in the ceremonial county of Somerset, known for its Roman-built baths. In 2011, the population was 88,859. Bath is in the valley of the River Avon, 97 miles (156 km) west of London and 11 miles (18 km) south-east of Bristol. The city became a World Heritage Site in 1987.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Bath,_Somerset"
  },
  { image: "assets/Marysons.jpg",
    imageSource: "forum.alexanderpalace.com",
    question: "The sister of two Kings and the daughter of one, this woman was known as whom?",
    answers: ["Victoria, Princess Royal", "Louise, Princess Royal and Duchess of Fife", "Anne, Princess Royal", "Mary, Princess Royal and Countess of Harewood"],
    correctAnswer: 3,
    answerFeedback: "Mary, Princess Royal and Countess of Harewood (Victoria Alexandra Alice Mary; 25 April 1897 to 28 March 1965) was a member of the British Royal Family; she was the third child and only daughter of King George V and Queen Mary. Two of her brothers ruled as King, though one for less than a year.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Mary,_Princess_Royal_and_Countess_of_Harewood"
  },
  { image: "assets/spice-island.jpg",
    imageSource: "tripadvisor.com",
    question: "Once part of the British Empire, India and it's food are quite popular in England.  When in London, where does one go to find the highest concentration of curry houses?",
    answers: ["Kensington", "Brick Lane", "Mayfair", "Westminster"],
    correctAnswer: 1,
    answerFeedback: "Brick Lane is a street in east London in the Borough of Tower Hamlets. Today, it is the heart of the city's Bangladeshi-Sylheti community and is known to some as Banglatown. It is famous for its many curry houses.",
    answerFeedbackSource: "Wikipedia, the free encyclopedia",
    link: "https://en.wikipedia.org/wiki/Brick_Lane"
  }
];